language: cpp

compiler:
    - clang
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - mkdir build
    - cd build
    - cmake ..
    - make 
    
jobs:
  include:
    - stage: test
      script: make test   

before_install:
    # Print used compiler versions.
    - gcc --version
    - clang --version
