language: cpp

compiler:
  - gcc
  - clang
script:
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - make test

before_install:
  # Print used compiler versions.
  - gcc --version
  - clang --version
