language: cpp

compiler:
    - clang
    - gcc


script:
    - mkdir build
    - cd build
    - cmake ..
    - make 
    
jobs:
  include:
    - stage: test
      script:
       - cd build
       - make test   

before_install:
    # Print used compiler versions.
    - gcc --version
    - clang --version
